### ISSUE TITLE
[Request] Latest Emoji 10.2

### ISSUE THREAD

**Issue by ikromy** [liuyuning/DumpEmoji#1]
Can you add latest emoji list from IOS 10.2 beta 3? actually I need the emoji order list to put in my android project. I search entire web cannot find, until I find this :smile: 

Thanks

**Comment by liuyuning** [comment]
Emoji files of iOS10.2 beta 2 added to the dir of "Emojis/".
After beta 3 released , I will update immediately.

**Comment by ikromy** [comment]
thank you

**Comment by liuyuning** [comment]
Please clone the latest emoji files, I have fixed the Skin Tone bug for iOS 10.
