### ISSUE TITLE
Missing Skin toned Emoji's

### ISSUE THREAD

**Issue by anthonycastelli** [liuyuning/DumpEmoji#2]
For example, this is missing from the skin tone emoji list. 👨‍🍳 I'm not sure what Apple i doing that this one doesn't have skin tones when exporting, but its there on the iOS Keyboard.

**Comment by liuyuning** [comment]
@anthonycastelli 
I have update the Skin Tone for iOS 10, clone the latest code and files.

**Comment by anthonycastelli** [comment]
Alright, cool, thanks!

**Comment by liuyuning** [comment]
fixed
